# Generated by Django 4.2.4 on 2023-08-29 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('user_password', models.CharField(max_length=128)),
                ('charging_station_name', models.CharField(max_length=100)),
                ('billing', models.DecimalField(decimal_places=2, max_digits=10)),
                ('charging_time', models.IntegerField()),
                ('charging_type', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
